# Generated by Django 4.1.3 on 2022-12-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_item_last_changer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logs',
        ),
    ]
