# Generated by Django 4.1.3 on 2022-12-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_delete_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
