# Generated by Django 4.1.3 on 2022-12-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_item_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('name', 'category_name'), name='unique_name_in_category'),
        ),
    ]
